#!/usr/bin/env bash
set -e

if [ "$1" = "" ]; then
  flake8="flake8"
  pip="pip"
  pygmentize="pygmentize"
else
  flake8="$1/flake8"
  pip="$1/pip"
  pygmentize="$1/pygmentize"
fi

if [ "$GIT_AUTHOR_DATE" ]; then
  # Existing $GIT_AUTHOR_DATE environment variable implies that it's executed
  # by Git as a pre-commit hooks.  In this case Git guarantees the current
  # working directory (CWD), i.e. $PWD, is the project root directory.
  project_root="$PWD"
elif env | grep '^GIT_PREFIX='; then
  # Existing $GIT_PREFIX environment variable implies that it's executed
  # by Git as a pre-push hooks.
  project_root="$PWD"
else
  project_root="$(dirname "$0")"
fi


if [ "$1" = "" ] && [ "$VIRTUAL_ENV" = "" ]; then
  echo 'You seem not in any virtual environment.  Stopped.' >> /dev/stderr
  exit 1
fi

eval "$flake8"

function test-requirements-order {
  tf="$(mktemp)"
  LC_COLLATE=C sort -f "$1" > "$tf"
  if [[ "$(cat "$tf")" != "$(cat "$1")" ]]; then
    {
      echo "List $1 in lexicographical order:"
      diff -u "$1" "$tf" | "$pygmentize" -l diff
      echo "You can utilize sort command:"
      echo "  LC_COLLATE=C sort -o '$1' -f '$1'"
    } >> /dev/stderr
    exit 1
  fi
}
test-requirements-order requirements.txt
test-requirements-order dev-requirements.txt
test-requirements-order prod-requirements.txt
